

export const frontConstants={
    siteName: 'Auto Server',
    subtitle: 'Marca registrada',
    metaData: {
        dataTitle:"Create Next App",
        dataDescription:"Generated by create next app",
        dataAutors:[
            { 
                name: "Thiago",
                url: "https://nextjs.org" 
            },
            { 
                name: "Bruno",
                url: "https://nextjs.org" 
            }
        ]
    },
    integracoes_path:[
        { name:'evolution', url:'http://localhost:8080/manager' },
        { name:'evolution postman', url:'https://www.postman.com/agenciadgcode/evolution-api/collection/1wphumy/evolution-api-v2-2-0-v2-2-1'},
        { name:'evolution github', url:'https://github.com/EvolutionAPI/evolution-api'},
        { name:'banco de dados', url:'http://localhost:8082'},
    ]


}