

export const frontConstants={
    siteName: 'Auto Server',
    subtitle: 'Marca registrada',
    metaData: {
        dataTitle:"Create Next App",
        dataDescription:"Generated by create next app",
        dataAutors:[
            { 
                name: "Thiago",
                url: "https://nextjs.org" 
            },
            { 
                name: "Bruno",
                url: "https://nextjs.org" 
            }
        ]
    },
    integracoes_path:[
        { name:'evolution', url:'http://localhost:8080/manager' },
        { name:'evolution documentação', url:'http://localhost:8080/manager'},
        { name:'banco de dados', url:'http://localhost:8082' },
    ]


}