version: '3.9'
services:
  app:
    image: thiago723/whatsappbot:0.0.4

    networks:
      - npm_public
      - wwp_bot

    environment:
      - SKIP_DB=true  #skipar o BD para fazer a build da imagem docker
      - AUTH_SECRET=BoySsEeu0SFtpZKBUVg9omevcSHlfyxzhc3JdhMOZ4U=

      - DATABASE_URL=postgresql://postgres:parangarito12@db:5432/bruno

      # NextAuth
      - NEXTAUTH_URL=https://zapqi.com.br
      - AUTH_TRUST_HOST=https://zapqi.com.br
      - NEXTAUTH_URL_INTERNAL=http://app:3099

      #- NEXTAUTH_URL_INTERNAL=https://zapqi.com.br
      - NEXTAUTH_SECRET=0johO5lljnbfY43sT0pmr8W3r1CWhuybfPS260SWHec=
      - TRUST_HOST=true

      # Evolution
      - EVOLUTION_URL=http://evolution-api:8080
      - EVOLUTION_APIKEY=minhasenhasecreta  
    ports:
      - 3099:3000


  # EVOLTION API ====================================
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    
    networks:
      - npm_public
      - wwp_bot

    environment:
      - SERVER_URL=http://localhost:8080
      - DEL_INSTANCE=false
      - AUTHENTICATION_API_KEY=minhasenhasecreta
      - CONFIG_SESSION_PHONE_NAME=click_digital
      
      - DATABASE_CONNECTION_URI=postgresql://postgres:parangarito12@db:5432/evolution
      - DATABASE_ENABLED=false
      - DATABASE_PROVIDER=postgresql
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - DATABASE_CONNECTION_CLIENT_NAME=evolution-api
      
      - WEBSOCKET_ENABLED=true
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBSOCKET_GLOBAL_EVENTS=false

      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evo_redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution-api
      - CACHE_REDIS_SAVE_INSTANCES=false
    

    ports:
      - "8080:8080"   
    volumes:
      - evolution_instances:/evolution/instances

  # IMAGEM DO N8N  ====================================
  n8n:
    image: n8nio/n8n:1.90.2

    networks:
      - npm_public
      - wwp_bot

    ports:
      - "5678:5678"
    environment:
      #- N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      #- N8N_PORT=5678
      #- N8N_PROTOCOL=https
      #- NODE_ENV=production
      #- WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=America_Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  flowise:
        image: flowiseai/flowise:2.2.6

        networks:
          - npm_public
          - wwp_bot

        environment:
         - FLOWISE_USERNAME=user
         - FLOWISE_PASSWORD=1234

        ports:
            - '4000:3000'
        
        volumes:
            - ~/.flowise:/root/.flowise
        entrypoint: /bin/sh -c "sleep 3; flowise start"


  # RabbitMq ====================================
  rabbitmq:
    image: rabbitmq:3-management

    networks:
      - npm_public
      - wwp_bot

    ports:
      - 5672:5672
      - 15672:15672  #dashboard
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

      
  # DB POSTGRES  ====================================
  db:
    image: postgres:latest

    networks:
      - npm_public
      - wwp_bot

    environment:
      POSTGRES_PASSWORD: parangarito12
      POSTGRES_DB: evolution
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  
  # PAINEL ADMIN DB ====================================
  adminer:
    image: adminer

    networks:
      - npm_public
      - wwp_bot

    ports:
      - "8082:8080"
    depends_on:
      - db
  
  # REDIS ====================================
  evo_redis:
    image: redis:latest

    networks:
      - npm_public
      - wwp_bot

    volumes:
      - ./evolution_redis:/data
    ports:
      - 6379:6379
  
  # REDIS Painel====================================
  redis-insight:
    image: redis/redisinsight:latest
    networks:
      - npm_public
      - wwp_bot

    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data


networks:
  npm_public:
    external: true
  wwp_bot:
    external: true

volumes:
  evolution_instances:
  pgdata:
  evolution_redis:
  redis-insight:
  n8n_data:
  local-files:
  rabbitmq_data: